mysql:
  host: 192.168.2.139
  port: 2881
  user: elabx@chemzero
  passwd: Elabx@123
  database: elabx

service:
  port: 8066
  backup: true
  uploadFileDir: /var/www/html/uploads/

redis:
  host: 192.168.2.139
  port: 4000

indigo:
  host: 192.168.2.139
  port: 8002

output:
  loglevel: info
  logfile: log/elabx_svr_web.log
  serviceLog: log/elabx_svr.log
